apiVersion: v1
kind: Service
metadata:
  name: watip
  labels:
    app: watip
spec:
  ports:
  - port: 7070
    targetPort: watip
  selector:
    app: watip

---

apiVersion: v1
kind: Pod
metadata:
  name: watip
  labels:
    app: watip
    role: master
spec:
  containers:
  - image: basilboli/whatismyipaddress:2.0.0
    name: watip
    ports:
    - name: watip
      containerPort: 7070